name: delaunay-parity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - h5py
  - jupyterlab
  - tqdm
  - cmake
  - cxx-compiler
  - cgal-cpp
  - gmp
  - mpfr
  - libboost-devel
  - pip